# Spring
spring:

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  # Jpa
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false

# Server
server:
  port: 8080

# Jwt
jwt:
  secret: saltingForSan
  expirationTime: 6000000000
  tokenPrefix: Bearer
  headerString: Authorization




